services:
  postgres:
    image: postgres:15
    container_name: scd_postgres
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    volumes:
      - scd_postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: scd_keycloak
    command:
      - start-dev
      - --db=postgres
      - --db-url=jdbc:postgresql://postgres:5432/keycloak
      - --db-username=keycloak
      - --db-password=keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    depends_on:
      - postgres

  frontend:
    build: ./services/frontend
    container_name: scd_frontend
    ports:
      - "3000:80"
    depends_on:
      - keycloak

volumes:
  scd_postgres_data:
